import os
import json
from pathlib import Path
import pandas as pd
import pymongo

def load_json_metrics(metrics_dir: Path, prefix: str, horizon: int) -> dict:
    """Safely extracts performance telemetry generated by the training engine."""
    file_path = metrics_dir / f"{prefix}_metrics_{horizon}h.json"
    if file_path.exists():
        with open(file_path, "r") as f:
            return json.load(f)
    return {}

def run_evaluation_suite():
    print("================================================================================")
    print("                    MLOPS SUITE: CROSS-MODEL EVALUATION                         ")
    print("================================================================================")
    
    # 1. Connect to MongoDB using the pipeline's secured environment variable
    mongo_uri = os.getenv("MONGODB_URI")
    if not mongo_uri:
        print("⚠️ Warning: MONGODB_URI environment variable not detected.")
        return

    try:
        client = pymongo.MongoClient(mongo_uri, serverSelectionTimeoutMS=5000)
        db = client["karachi_aqi"]
        print("🔗 Successfully linked validation hook to MongoDB cluster.")
    except Exception as e:
        print(f"❌ Failed to connect to MongoDB: {e}")
        return

    # 2. Establish directory context and dynamically extract metrics files
    SCRIPT_DIR = Path(__file__).resolve().parent
    BASE_DIR = SCRIPT_DIR.parent if SCRIPT_DIR.name == "training_pipeline" else SCRIPT_DIR
    METRICS_DIR = BASE_DIR / "metrics"

    print(f"\n📝 Compiling final operational metrics from: {METRICS_DIR.name}/")
    
    horizons = [24, 48, 72]
    model_mappings = {
        "Random Forest": "rf",
        "XGBoost": "xgb",
        "Ridge": "ridge"
    }

    compiled_horizons = {}

    for h in horizons:
        horizon_key = f"{h}h"
        # Separate models dictionary from the meta winning property
        compiled_horizons[horizon_key] = {
            "models": {},
            "Winning_Model": "None"
        }
        
        best_engine = "None"
        best_mae = float("inf")
        
        for model_name, prefix in model_mappings.items():
            raw_metrics = load_json_metrics(METRICS_DIR, prefix, h)
            
            mae = raw_metrics.get("test_mae")
            r2 = raw_metrics.get("test_r2")
            mape = raw_metrics.get("test_mape")
            coverage = raw_metrics.get("conformal_global_coverage")
            
            compiled_horizons[horizon_key]["models"][model_name] = {
                "MAE": float(mae) if mae is not None else None,
                "R2": float(r2) if r2 is not None else None,
                "MAPE": float(mape) if mape is not None else None,
                "Coverage": float(coverage) if coverage is not None else None
            }
            
            # Dynamically identify the winning model based on MAE optimization
            if mae is not None and mae < best_mae:
                best_mae = mae
                best_engine = model_name
            elif mae is not None and mae == best_mae:
                best_engine = f"{best_engine} / {model_name}"
                
        compiled_horizons[horizon_key]["Winning_Model"] = best_engine

    # 3. Print complete, multi-metric comprehensive dashboard to GitHub Runner log
    print("\n" + "="*95)
    print(f"{'Horizon':<8} | {'Forecasting Engine':<15} | {'MAE':>10} | {'MAPE':>10} | {'R² Score':>12} | {'Coverage':>12}")
    print("="*95)
    
    for h in horizons:
        horizon_key = f"{h}h"
        for model_name in model_mappings.keys():
            m_stats = compiled_horizons[horizon_key]["models"][model_name]
            
            mae_str = f"{m_stats['MAE']:.1f}" if m_stats['MAE'] is not None else "N/A"
            mape_str = f"{m_stats['MAPE']:.2f}%" if m_stats['MAPE'] is not None else "N/A"
            r2_str = f"{m_stats['R2']:.3f}" if m_stats['R2'] is not None else "N/A"
            cov_str = f"{m_stats['Coverage']*100:.1f}%" if m_stats['Coverage'] is not None else "N/A"
            
            print(f"{horizon_key:<8} | {model_name:<15} | {mae_str:>10} | {mape_str:>10} | {r2_str:>12} | {cov_str:>12}")
        
        print(f"🏆 Winning Engine ({horizon_key}): {compiled_horizons[horizon_key]['Winning_Model']}")
        print("-" * 95)

    # 4. Push complete production payload structure directly into a dedicated metrics collection
    try:
        payload = {
            "type": "automated_pipeline_evaluation",
            "timestamp": pd.Timestamp.now(tz="UTC").to_pydatetime(),  # Keep timestamps timezone-aware
            "pipeline_run_status": "SUCCESS",
            "performance_summary": compiled_horizons
        }
        
        # FIXED: Routing performance telemetry away from features matrix to isolated warehouse
        db["model_metrics"].insert_one(payload)
        print("🚀 Performance history record successfully pushed to MongoDB Atlas.")
    except Exception as e:
        print(f"⚠️ Could not log metrics to database: {e}")

    print("\n✅ Evaluation validation complete. Models verified and approved for dashboard delivery.")

if __name__ == "__main__":
    run_evaluation_suite()